Python 3.10.4 (tags/v3.10.4:9d38120, Mar 23 2022, 23:13:41) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license()" for more information.

==== RESTART: C:/Users/maxna/AppData/Local/Programs/Python/Python310/1 36.py ===

==== RESTART: C:/Users/maxna/AppData/Local/Programs/Python/Python310/1 36.py ===
1605.593889740789

==== RESTART: C:/Users/maxna/AppData/Local/Programs/Python/Python310/1 36.py ===
1605.593889740789

==== RESTART: C:/Users/maxna/AppData/Local/Programs/Python/Python310/1 36.py ===
40.881474528780636

==== RESTART: C:/Users/maxna/AppData/Local/Programs/Python/Python310/1 36.py ===
2228.0801499661943

==== RESTART: C:/Users/maxna/AppData/Local/Programs/Python/Python310/1 36.py ===
35412349

==== RESTART: C:/Users/maxna/AppData/Local/Programs/Python/Python310/1 36.py ===
-35412349

==== RESTART: C:/Users/maxna/AppData/Local/Programs/Python/Python310/1 36.py ===
Traceback (most recent call last):
  File "C:/Users/maxna/AppData/Local/Programs/Python/Python310/1 36.py", line 8, in <module>
    print (main(-27))
  File "C:/Users/maxna/AppData/Local/Programs/Python/Python310/1 36.py", line 3, in main
    return 44*y**6 + 1
NameError: name 'y' is not defined

==== RESTART: C:/Users/maxna/AppData/Local/Programs/Python/Python310/1 36.py ===
Traceback (most recent call last):
  File "C:/Users/maxna/AppData/Local/Programs/Python/Python310/1 36.py", line 8, in <module>
    print (main(-27))
  File "C:/Users/maxna/AppData/Local/Programs/Python/Python310/1 36.py", line 3, in main
    return 44*y**6 + 1
NameError: name 'y' is not defined

==== RESTART: C:/Users/maxna/AppData/Local/Programs/Python/Python310/1 36.py ===
17046501517
